### PR TITLE
cancel-backfill: Add exclude/include-pools options

### PR DESCRIPTION
**Pull request by BenoitKnecht**
Only cancel backfills for PGs belonging to the set of pools selected by `--exclude-pools`/`--include-pools`.

Pools can be specified by integer ID or by name.

### CODE REVIEW

**Comment by baergj** [comment]
Looks good other than the test failure! Turns out that test failure is partially our fault - https://github.com/digitalocean/pgremapper/pull/39 will fix up the test implementation and then you can add pool 2 to setupTest() once you pull those changes in.

**Comment by BenoitKnecht** [comment]
I was a bit perplexed as to why `TestCalcPgMappingsToUndoBackfill` is failing here, as it was working fine in my environment, but I think it's because it runs `osdPoolDetails()` for real (as opposed to using hard-coded JSON) as part of `reorderUpToMatchActing()`, and I assume there's no pool ID 2 in the test environment.

I could remove PG 2.* from the tests, but then it wouldn't exercise much of the exclude/include pools code path. So is there an easy way to add a pool in the test environment?

**Comment by BenoitKnecht** [comment]
@baergj Race condition with my comment. :) I'll look into #39 now...

**Review by baergj — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
