### PR TITLE
nit: break for loop

### PR DESCRIPTION
**Pull request by microyahoo**
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

### CODE REVIEW

**Review by baergj — APPROVED** [review]
:+1:

**Comment by baergj** [comment]
@microyahoo Regarding that ticket - Wow, that's quite the disparity! Does `ceph pg ls` show that there's a huge difference between PG sizes?

I wonder also if this is because of the number of pools involved; pgremapper doesn't pay attention to pool balance (`balance-bucket` was built assuming a single pool per root and thus doesn't have much intelligence). Could it be that some OSDs are taking more of one pool than another, causing the imbalance?

The only other thought I had was whether the OSDs were deployed with different `bluestore_min_alloc_size`.

**Comment by microyahoo** [comment]
hi @baergj, I set the `target_size_ratio` of pools by mistake as multiple pools sharing the same raw capacity. After I adjust it, a large number of pgs are in the backfill state.
```console
[root@node01 smd]# ceph osd pool autoscale-status
POOL                                      SIZE  TARGET SIZE                RATE  RAW CAPACITY   RATIO  TARGET RATIO  EFFECTIVE RATIO  BIAS  PG_NUM  NEW PG_NUM  AUTOSCALE  BULK   
device_health_metrics                   291.9M                              3.0        48289G  0.0000                                  1.0       1              on         False  
deeproute-replica-hdd-pool              12613M                              3.0        785.8T  0.0010        0.1000           0.0010   1.0      32              on         False  
deeproute-replica-ssd-pool              12352G                              3.0        48289G  0.9901       50.0000           0.9901   1.0    1024              on         False  
.rgw.root                                5831                               3.0        48289G  0.0099        0.5000           0.0099   1.0       8              on         False  
default.rgw.log                           182                               3.0        48289G  0.0000                                  1.0      32              on         False  
default.rgw.control                         0                               3.0        48289G  0.0000                                  1.0      32              on         False  
default.rgw.meta                            0                               3.0        48289G  0.0000                                  4.0       8              on         False  
os-dsglczutvqsgowpz.rgw.control             0                               3.0        16096G  0.1667        0.5000           0.1667   1.0      64              on         False  
os-dsglczutvqsgowpz.rgw.meta            104.2k                              3.0        16096G  0.1667        0.5000           0.1667   1.0      64              on         False  
os-dsglczutvqsgowpz.rgw.buckets.index   57769M                              3.0        16096G  0.1667        0.5000           0.1667   1.0      32              on         False  
os-dsglczutvqsgowpz.rgw.buckets.non-ec  496.5M                              3.0        16096G  0.1667        0.5000           0.1667   1.0      32              on         False  
os-dsglczutvqsgowpz.rgw.log             309.0M                              3.0        16096G  0.1667        0.5000           0.1667   1.0      32              on         False  
os-dsglczutvqsgowpz.rgw.buckets.data    147.7T               1.3333333730697632        785.8T  0.7992       80.0000           0.7992   1.0    1024              on         False  
cephfs-metadata                          3231M                              3.0        16096G  0.0006                                  4.0      32              on         False  
cephfs-replicated-pool                  23137G                              3.0        785.8T  0.1998       20.0000           0.1998   1.0     128              on         False  
.nfs                                    100.1k                              3.0        48289G  0.0000                                  1.0      32              on         False  
os-dsglczutvqsgowpz.rgw.otp                 0                               3.0        16096G  0.1667        0.5000           0.1667   1.0       8              on         False
```
```
[root@node01 smd]# ceph -s
  cluster:
    id:     f7f1c8ba-f793-436b-bb73-0964108a30c1
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 8w)
    mgr: a(active, since 3w), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 108 osds: 108 up (since 19h), 108 in (since 4M); 104 remapped pgs
    rgw: 9 daemons active (9 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   17 pools, 5787 pgs
    objects: 160.99M objects, 181 TiB
    usage:   304 TiB used, 545 TiB / 849 TiB avail
    pgs:     119776974/1218292354 objects misplaced (9.832%)
             5683 active+clean
             102  active+remapped+backfill_wait
             2    active+remapped+backfilling
 
  io:
    client:   9.4 MiB/s rd, 87 MiB/s wr, 1.79k op/s rd, 2.34k op/s wr
    recovery: 11 MiB/s, 7 objects/s
 
  progress:
    Global Recovery Event (0s)
      [............................]
```

**Comment by baergj** [comment]
@microyahoo You may want to ask on the ceph-users mailing list if you want more help with your OSD balancing. It's also possible that this is a situation that https://github.com/TheJJ/ceph-balancer could help with.

**Comment by microyahoo** [comment]
> @microyahoo You may want to ask on the ceph-users mailing list if you want more help with your OSD balancing. It's also possible that this is a situation that https://github.com/TheJJ/ceph-balancer could help with.

thanks for you sharing.

**Pull request merged**
